package top.huangsansui.blog.dao;

import top.huangsansui.blog.model.ArticleTag;

public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long articleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated
     */
    int insert(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated
     */
    int insertSelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated
     */
    ArticleTag selectByPrimaryKey(Long articleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleTag record);
}